name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - markaggar
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        **Please provide as much detail as possible to help us diagnose the issue quickly.**
        
  - type: dropdown
    id: version
    attributes:
      label: Media Card Version
      description: What version of the media card are you running? (Check the first line in browser console)
      options:
        - Lastest version
        - v5.4.0 
        - v5.3.0
        - v5.1.0
        - v5.0.0
        - v4.1.0
        - v4.0.0
        - Earlier version
      default: 0
    validations:
      required: true
      
  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant are you running?
      placeholder: e.g., 2024.11.3
    validations:
      required: true
      
  - type: input
    id: media-index-version
    attributes:
      label: Media Index Version (if using Media Index)
      description: |
        If using Media Index integration, what version is installed? 
        Check Settings → Devices & Services → Media Index → click the integration → look for version in the info section.
      placeholder: e.g., v1.4.0, v1.3.0, or leave blank if not using Media Index
    validations:
      required: false
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen instead
      placeholder: |
        When I click the refresh button, the image doesn't reload...
        
        Expected: Image should reload with cache-busting timestamp
        Actual: Same cached image displays
    validations:
      required: true
      
  - type: textarea
    id: card-config
    attributes:
      label: Card YAML Configuration
      description: |
        **REQUIRED**: Please paste your complete card configuration (sanitize any sensitive paths/tokens)
        Open your dashboard in edit mode, click the card's edit button, then switch to "Show code editor" to copy the YAML.
      placeholder: |
        type: custom:media-card
        folder:
          path: /media/Photo/PhotoLibrary
          mode: random
        metadata:
          show_folder: true
          show_date: true
        # ... rest of your config
      render: yaml
    validations:
      required: true
      
  - type: textarea
    id: media-index-config
    attributes:
      label: Media Index Sensor Attributes (if applicable)
      description: |
        If using Media Index integration, go to Developer Tools → States, find your sensor (e.g., `sensor.media_index_media_photo_total_files`), and paste the **attributes** section here.
        This helps diagnose database/scanning issues.
      placeholder: |
        base_folder: /media/Photo/PhotoLibrary
        media_source_uri: media-source://media_source/media/Photo/PhotoLibrary
        total_files: 15234
        images_count: 14890
        videos_count: 344
        # ... other attributes
      render: yaml
    validations:
      required: false
      
  - type: textarea
    id: console-logs
    attributes:
      label: Browser Console Logs
      description: |
        **HIGHLY RECOMMENDED**: Open browser Developer Tools (F12), go to Console tab, reproduce the issue, then copy/paste any error messages or relevant logs.
        Look for lines starting with `[MediaCard]` or error stack traces.
      placeholder: |
        [MediaCard] MEDIA-CARD v5.4.0 Loaded
        [MediaCard] Initializing with config: {...}
        Error: Failed to load media - 404 Not Found
        ... stack trace ...
      render: shell
    validations:
      required: false
      
  - type: dropdown
    id: browsers
    attributes:
      label: What browser are you seeing the problem on?
      multiple: true
      options:
        - Chrome/Edge (Chromium-based)
        - Firefox
        - Safari
        - Home Assistant Companion App (iOS)
        - Home Assistant Companion App (Android)
        
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add screenshots, workarounds you've tried, or any other relevant information
    validations:
      required: false
